[WIP] flux-account.py: fix add-user, edit-user, edit-bank, add sharness tests for python subcommands
flux-framework/flux-accounting pull request #140
Opened 2021-08-31 15:15 UTC by cmoussa1

_note: this PR is built on top of #131, so I will leave this as [WIP] until that PR is merged and then I will rebase._

_note: this PR will round out the `0.9.0` release for flux-accounting._

I noticed while doing some interactive things with **flux-account.py** that a couple subcommands were broken/not working as expected, mostly because of some missing args that came partly as a result from #124 and from a general lack of testing. This PR includes some various minor fixes to a couple of the subcommands.

I also am looking to add a set of tests for **flux-acount.py** to hopefully prevent bugs like this from creeping into the code in the future. These tests use the basic subcommands that interact with user and bank accounts in the flux-accounting DB, such as adding a user account, editing some fields, adding a bank, and removing a bank, just to name a few.

Fixes #137

2021-09-01 22:10 UTC, grondo requested changes
Overall LGTM.

Some of the commit messages could use message bodies. These really help in the future when you are trying to understand the context of why a change was made.
In flux-core, we've adopted the practice of using a `Problem:` statement, stating the problem that the commit fixes, and then in a second paragraph describe the solution. This isn't necessarily a requirement, but does seem to help when looking back at commits, and helps you ensure you are making a commit that addresses a single, stateable problem.

For this PR, I'd encourage at least some commit message body for all commits though.

2021-09-01 22:38 UTC, cmoussa1 commented
Thanks @grondo - that's totally reasonable, and a good idea for me to adopt here too. Thanks for pointing this out. I'll go ahead and add some message bodies to the commits and force push those changes up.

2021-09-02 19:50 UTC, grondo approved these changes
Nice job updating the commit messages! LGTM!

2021-09-02 22:20 UTC, cmoussa1 commented
Woohoo! Thanks @grondo. I'll go ahead and set MWP.

2021-09-02 23:13 UTC, merged